name: 01 - building - blocks
on: push
jobs:
  echo-hello:
    runs-on: self-hosted
    steps:
        - name: say hello
          run: echo "hello word"
  echo-goodbye:
    runs-on: ubuntu_latest
    steps:
        - name: failed step  
          run: |

            echo "will succeed"
            exit 0
        - name: say goodbye
          run: echo "goodbye"
          
