name: 01 - building - blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu_latest
    steps:
        - name: say hello
          run: echo "hello word"
  echo-goodbye:
    runs-on: ubuntu_latest
    steps:
        - name: failed step
          run: |
          echo "I will fail"
          exit 1
        - name: goodbye
          run: echo "Goodbye"

