name: 03-workflow-runner
on: 
  push:
  repository_dispatch:
   types:   [10 Controlling the execution flow]
  
jobs:

   Linux-runner: 
            runs-on: ubuntu-latest
            steps:
             - name: show runners
               run: echo "I am running "$RUNNER_OS" runner"

   windows-runner:
            runs-on: windows-latest
            
            steps:
              - name: show OS
                shell: bash
                run: echo "I am running on "$RUNNER_OS" runner"
   macos-runner:
            runs-on: macos-latest
            steps:
              - name: show OS
                run: echo "I am running on "$RUNNER_OS" runner"



                





  














