name: 03-workflow-runner
on: 
  push:
jobs:
   Linux-runner: 
            runs-on: self-hosted
            steps:
             - name: show runners
               run: echo "I am running "$RUNNER_OS" runner"

   windows-runner:
            runs-on: windows-latest
            
            steps:
              - name: show OS
                shell: bash
                run: echo "I am running on "$RUNNER_OS" runner"
   macos-runner:
            runs-on: mac-os latest
            steps:
              - name: show OS
                run: echo "I am running on "$RUNNER_OS" runner"




