name: 04 - using actions
on: push
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: checkout cpde
        uses: action/checkout@v4
      - name: printing folders
        run: ls
        
     #0.Checkout the code from repo
     #Install deps of our react application
     #2.Executae automated tests
     
