name: 10 Controlling the execution flow
#Executing jobs parallel way#
on: 
  # push:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
       type: boolean
       description: whether unit test will run or not  
       default: true
       
jobs:

  lint-build:
      runs-on: ubuntu-latest
      needs: []
      steps:
       - name: lint and build
         run: |
              echo "running and building"
              
          
  unit-tests:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
      - name: Running unit tests
        run: echo "Runnings test..."
      - name: failing steps 
        if: ${{!inputs.pass-unit-tests}}
        run: exit 1 
  deploy-nonprod:
      runs-on: ubuntu-latest
      needs:
         []
      steps:
      - name: Deploying to non prod
        run: echo "Deploying to non prod"
  



         










         


         






         

         


        
