name: 11-working with inputs  
on:
  push:
  workflow_dispatch:
  
   inputs:
      dry-run:
         type: boolean
         description: skip deployment and only print build output
         default: false  
      target:
       type: environment
       required: true
       description: which environment workflow will target
      tag:
       type: choice
       options:
         - v1
         - v2
         - v3
       default: v3
       description: Release from which to deploy
        
jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: build
       run: echo "buildng from tag ${{inputs.tag}}"
  deploy: 
    runs-on: self-hosted
    if: ${{!inputs.target }}
    environment: ${{inputs.target}}
    steps:
     - name: Deploy
       run: echo "deploying to ${{inputs.target}}"
    
    
