name: 18.1 -Reusable workflows-Reusable definition
on: 
  push:
  workflow_call:
     inputs: 
        target-directory:
           
             type: string
             required: true
     outputs:
              build-status:
                  description: THe status of build process.
                  value: ${{jobs.deploy.outputs.build-status}}
              url:
                  description: URL of deployed version
                  value: $ {{jobs.deploy.outputs.url}}



jobs:
   deploy:
      runs-on: self-hosted
      outputs: 
          build-status: ${{steps.build.outputs.build-status}}
          url: ${{steps.deploy.outputs.outputs.url}}
      steps: 
         - name: Checkout repo
           uses: actions/checkout@v4
         - name: build
           id: build  
           run: |
              echo "Building using directory ${{inputs.target-directory}}"
              echo "build-status=success" >> "$GTHUB_OUTPUt"
         - name: Deploy
           id: deploy
           run: |
              echo "Deploying the artifacts"
              echo "url=https://www.google.com" >> "$GTHUB_OUTPUt"





              
