name: 18.2-Reusbale-workflow
on:
  push:
  workflow_dispatch:
jobs:
  some-job: 
  
    uses: ./.github/workflows/18-1-resusable-workflows.yaml
    with: 
      target-directory: dummy-dir
  prints-outputs: 
     runs-on: ubuntu-latest
     needs: some-job
     steps: 
      - name: print outputs
        run: |
          echo "Build status: ${{needs.deploy.outputs.build-status}}"
          echo "URL: ${{needs.deploy.outputs.url}}"
















          
      
